test trigger

diff --git a/.github/workflows/scenario-runner.yml b/.github/workflows/scenario-runner.yml
--- a/.github/workflows/scenario-runner.yml
+++ b/.github/workflows/scenario-runner.yml
@@ -25,13 +25,21 @@ on:
   # Developers should add this to their branch's workflow
   # in order to register an event.
   pull_request:
+    types:
+      - opened
+      - synchronize
+      - ready_for_review
+    paths:
+      - '.github/'
     branches:
       - develop
       - master
-  push:
-    branches:
-      - develop
-      - master
+
+
+env:
+  ACTION_REGISTER_EVENT: ""
+  EXPERIMENTS_DIR: "${{ github.event.inputs.experiments_dir }}"
+  DEBUG_ENABLED: "${{ github.event.inputs.debug_enabled }}"
 
 
 jobs:
@@ -47,86 +55,107 @@ jobs:
   # [register action] | Register a workflow_dispatch event
   # [skip ci]         | Skip the workflow
 
-  register_action:
+  workflow_setup:
+    # uses: ./.github/actions/workflow_setup/action.yml
     name: 📝 Register Action
     runs-on: ubuntu-latest
-    # if: "github.event_name == 'push'"
-    outputs:
-      register_action: ${{ steps.register_action.outputs.register_event }}
+    if: ${{ github.event_name == 'pull_request' }}
+    # if: ${{ github.event_name == 'pull_request' && contains(github.event.comment.body, '!workflow register') }}
+    # outputs:
+    #   register_action: ${{ steps.register_action.outputs.register_event }}
     steps:
+      # - name: 🐄 Got git?
+      #   uses: actions/checkout@v3
+
       - name: 📝 Register Action
         id: register_action
         run: |
-          echo "::set-output name=register_event::$(echo ${{ github.event.head_commit.message }} | grep -q '\[register action\]' && echo true || echo false)"
-
+          echo "::set-output name=register_event::$(echo ${{ github.event.comment.body }} | grep -q '!workflow register' && echo true || echo false)"
+      # - name: 📝 Register Action
+      #
+      #   run: |
+      #     echo "::set-output name=register_event::$(echo ${{ github.event.comment.body }} | grep -q '!workflow register' && echo true || echo false)"
 
   matrix_generator:
     name: Matrix Generator
     runs-on: ubuntu-latest
-    needs: [register_action]
-    if: ${{ needs.register_action.outputs.register_event == 'false' }}
-    outputs:
-      matrix: ${{ steps.generate-matrix.outputs.matrix }}
+    needs:
+      - workflow_setup
+    if: ${{ needs.workflow_setup.outputs.register_event != 'true' }}
     steps:
-      - name: 🐄 Got git?
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: 👩‍💻 Generating Matrix
-        id: generate-matrix
+      - name: Test
         run: |
-          echo "::set-output name=matrix::$(find ./scenario_configs/${{ github.event.inputs.experiments_dir }} -type f -name "*.json" | jq -cnR '[inputs | select(length>0)]')"
+          echo "TEST"
+          pwd
+          ls -lisa
+
+  # matrix_generator:
+  #   name: Matrix Generator
+  #   runs-on: ubuntu-latest
+  #   needs: [workflow_setup]
+  #   if: ${{ needs.workflow_setup.outputs.register_event != 'true' }}
+  #   outputs:
+  #     matrix: ${{ steps.generate-matrix.outputs.matrix }}
+  #   steps:
+  #     - name: 🐄 Got git?
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+
+  #     - name: 👩‍💻 Generating Matrix
+  #       id: generate-matrix
+  #       run: |
+  #         echo "::set-output name=matrix::$(find ./scenario_configs/${{ github.event.inputs.experiments_dir }} -type f -name "*.json" | jq -cnR '[inputs | select(length>0)]')"
 
 
-  matrix_job:
-    runs-on: ubuntu-latest
-    needs: matrix_generator
-    strategy:
-      fail-fast: false
-      matrix:
-        scenario_path: ${{ fromJson(needs.matrix_generator.outputs.matrix) }}
-    steps:
-      - name: 🐄 Got git?
-        uses: actions/checkout@v3
+  # matrix_job:
+  #   runs-on: ubuntu-latest
+  #   needs: matrix_generator
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       scenario_path: ${{ fromJson(needs.matrix_generator.outputs.matrix) }}
+  #   steps:
+  #     - name: 🐄 Got git?
+  #       uses: actions/checkout@v3
 
-      - name: 🐍 Setup Environment
-        uses: ./.github/actions/evaluations_environment_setup
+  #     - name: 🐍 Setup Environment
+  #       uses: ./.github/actions/evaluations_environment_setup
 
-      - name: ⚒️ Install Prerequisites
-        run: |
-          source .venv/bin/activate
+  #     - name: ⚒️ Install Prerequisites
+  #       run: |
+  #         source .venv/bin/activate
 
-      - name: 🚀 Run Scenario Evaluation
-        timeout-minutes: 30
-        env:
-          ARMORY_INSTALL: "/tmp"
-          HOME: "/tmp"
-        run: |
-          mkdir -p "/tmp/logs"
+  #     - name: 🚀 Run Scenario Evaluation
+  #       timeout-minutes: 30
+  #       env:
+  #         ARMORY_INSTALL: "/tmp"
+  #         HOME: "/tmp"
+  #       run: |
+  #         mkdir -p "/tmp/logs"
 
-          mkdir -p "${HOME}/armory/outputs/"
-          mkdir -p "${HOME}/.armory/"
+  #         mkdir -p "${HOME}/armory/outputs/"
+  #         mkdir -p "${HOME}/.armory/"
 
-          armory configure --use-defaults
+  #         armory configure --use-defaults
 
-          pytest \
-            -c pyproject.toml \
-            --verbose \
-            -s ./tests/end_to_end/test_scenario_runner.py \
-            --scenario-path ${{ matrix.scenario_path }} \
-            --github-ci | tee "scenario_evaluation.log"
+  #         pytest \
+  #           -c pyproject.toml \
+  #           --verbose \
+  #           -s ./tests/end_to_end/test_scenario_runner.py \
+  #           --scenario-path ${{ matrix.scenario_path }} \
+  #           --github-ci | tee "scenario_evaluation.log"
 
 
-      - name: 📁 Archiving Artifacts
-        uses: actions/upload-artifact@v3
-        # if: ${{ !failure() }}
-        continue-on-error: true
-        with:
-          name: evaluation-artifacts
-          retention-days: 1
-          path: |
-            /tmp/logs/
-            /tmp/results/
-            /tmp/armory/outputs/
-            /tmp/.armory/outputs/
+  #     - name: 📁 Archiving Artifacts
+  #       uses: actions/upload-artifact@v3
+  #       # if: ${{ !failure() }}
+  #       continue-on-error: true
+  #       with:
+  #         name: evaluation-artifacts
+  #         retention-days: 1
+  #         path: |
+  #           /tmp/logs/
+  #           /tmp/results/
+  #           /tmp/armory/outputs/
+  #           /tmp/.armory/outputs/
